### ISSUE TITLE
ImportError: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by d123456ddq** [cardwing/Codes-for-Lane-Detection#146]
Traceback (most recent call last):
  File "test_erfnet.py", line 13, in <module>
    from models import sync_bn
  File "/home/liaowu/semantic_segmentation/Codes-for-Lane-Detection/ERFNet-CULane-PyTorch/models/sync_bn/__init__.py", line 1, in <module>
    from .functions.sync_bn import *
  File "/home/liaowu/semantic_segmentation/Codes-for-Lane-Detection/ERFNet-CULane-PyTorch/models/sync_bn/functions/__init__.py", line 1, in <module>
    from .sync_bn import *
  File "/home/liaowu/semantic_segmentation/Codes-for-Lane-Detection/ERFNet-CULane-PyTorch/models/sync_bn/functions/sync_bn.py", line 6, in <module>
    from .._ext import sync_bn_lib
  File "/home/liaowu/semantic_segmentation/Codes-for-Lane-Detection/ERFNet-CULane-PyTorch/models/sync_bn/_ext/sync_bn_lib/__init__.py", line 2, in <module>
    from ._sync_bn_lib import lib as _lib, ffi as _ffi
ImportError: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory

Thank you for you lane-detection code.
When i sh test_erfnet.sh in ERFnet-CULane-pytorch, get this error.

**Comment by cardwing** [comment]
It should be related to the lib files of python 3.5. Have you installed python 3.5?
