### ISSUE TITLE
When running test_lanenet.py, "NotFoundError:" is appearing

### ISSUE THREAD

**Issue by AravindHemachandran** [cardwing/Codes-for-Lane-Detection#168]
`self.dataset_info_file /media/aravind/Applications/Datasets/Lanes/CULane/driver_100_30frame/05251517_0433.MP4/00720.lines.txt
2019-10-14 10:18:20.130660: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2019-10-14 10:18:20.130694: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2019-10-14 10:18:20.130701: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2019-10-14 10:18:20.130707: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2019-10-14 10:18:20.130712: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2019-10-14 10:18:20.220626: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-10-14 10:18:20.221007: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties: 
name: GeForce 940MX
major: 5 minor: 0 memoryClockRate (GHz) 1.189
pciBusID 0000:01:00.0
Total memory: 1.96GiB
Free memory: 1.63GiB
2019-10-14 10:18:20.221024: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2019-10-14 10:18:20.221030: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2019-10-14 10:18:20.221039: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce 940MX, pci bus id: 0000:01:00.0)
INFO:tensorflow:Restoring parameters from /media/aravind/Applications/Datasets/Lanes/CULane/SCNN-pretrainedModelForTesting/culane_lanenet_vgg_2018-12-01-14-38-37.ckpt-10000
I1014 10:18:20.789147 10250 tf_logging.py:82] Restoring parameters from /media/aravind/Applications/Datasets/Lanes/CULane/SCNN-pretrainedModelForTesting/culane_lanenet_vgg_2018-12-01-14-38-37.ckpt-10000
0
**2019-10-14 10:18:21.003016: W tensorflow/core/framework/op_kernel.cc:1192] Not found: 88.538
2019-10-14 10:18:21.003052: W tensorflow/core/framework/op_kernel.cc:1192] Not found: 302.39
2019-10-14 10:18:21.003083: W tensorflow/core/framework/op_kernel.cc:1192] Not found: 88.538
	 [[Node: map/while/ReadFile = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](map/while/TensorArrayReadV3)]]
2019-10-14 10:18:21.003091: W tensorflow/core/framework/op_kernel.cc:1192] Not found: 675.56**
**Traceback (most recent call last):**
  File "/home/aravind/anaconda3/envs/tensorflow_gpu/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/aravind/anaconda3/envs/tensorflow_gpu/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "/home/aravind/anaconda3/envs/tensorflow_gpu/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/aravind/anaconda3/envs/tensorflow_gpu/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
**tensorflow.python.framework.errors_impl.NotFoundError: 88.538
	 [[Node: map/while/ReadFile = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](map/while/TensorArrayReadV3)]]**

**During handling of the above exception, another exception occurred:**

**Traceback (most recent call last):**
  File "tools/test_lanenet.py", line 125, in <module>
    test_lanenet(args.image_path, args.weights_path, args.use_gpu, img_name, args.batch_size, save_dir)
  File "tools/test_lanenet.py", line 84, in test_lanenet
    feed_dict={input_tensor: paths})
  File "/home/aravind/anaconda3/envs/tensorflow_gpu/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/aravind/anaconda3/envs/tensorflow_gpu/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/aravind/anaconda3/envs/tensorflow_gpu/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/aravind/anaconda3/envs/tensorflow_gpu/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: 88.538
	 [[Node: map/while/ReadFile = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](map/while/TensorArrayReadV3)]]

Caused by op 'map/while/ReadFile', defined at:
  File "tools/test_lanenet.py", line 125, in <module>
    test_lanenet(args.image_path, args.weights_path, args.use_gpu, img_name, args.batch_size, save_dir)
  File "tools/test_lanenet.py", line 60, in test_lanenet
    imgs = tf.map_fn(test_dataset.process_img, input_tensor, dtype=tf.float32)
  File "/home/aravind/anaconda3/envs/tensorflow_gpu/lib/python3.5/site-packages/tensorflow/python/ops/functional_ops.py", line 389, in map_fn
    swap_memory=swap_memory)
  File "/home/aravind/anaconda3/envs/tensorflow_gpu/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2775, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/home/aravind/anaconda3/envs/tensorflow_gpu/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2604, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/aravind/anaconda3/envs/tensorflow_gpu/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2554, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/aravind/anaconda3/envs/tensorflow_gpu/lib/python3.5/site-packages/tensorflow/python/ops/functional_ops.py", line 379, in compute
    packed_fn_values = fn(packed_values)
  File "/media/aravind/Applications/Datasets/Lanes/CULane/SCNN_SourceCode/Codes-for-Lane-Detection-master/SCNN-Tensorflow/lane-detection-model/data_provider/lanenet_data_processor_test.py", line 59, in process_img
    img_raw = tf.read_file(img_path)
  File "/home/aravind/anaconda3/envs/tensorflow_gpu/lib/python3.5/site-packages/tensorflow/python/ops/gen_io_ops.py", line 223, in read_file
    result = _op_def_lib.apply_op("ReadFile", filename=filename, name=name)
  File "/home/aravind/anaconda3/envs/tensorflow_gpu/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/aravind/anaconda3/envs/tensorflow_gpu/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/aravind/anaconda3/envs/tensorflow_gpu/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

**NotFoundError (see above for traceback): 88.538
	 [[Node: map/while/ReadFile = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](map/while/TensorArrayReadV3)]]**`

Can someone clarify as to what this error is?
_Also is there a way to run the test_lanenet.py on just a CPU?_

**Comment by cardwing** [comment]
I have not met this problem before. Please debug by yourself. And running testing codes on CPU is very slow. You can refer to the official tutorial for more details.

**Comment by AravindHemachandran** [comment]
I'll update if I find any solutions
