### ISSUE TITLE
Import Error in ERFNet-CULane-PyTorch

### ISSUE THREAD

**Issue by fantasycheng** [cardwing/Codes-for-Lane-Detection#174]
I use Anaconda to install PyTorch 1.3 with python=3.7.4, opencv=3.1.
But when I run the test_erfnet.sh, it show messages like that

> Traceback (most recent call last):
  File "test_erfnet.py", line 13, in <module>
    from models import sync_bn
  File "/home/ssd500A/adas/Codes-for-Lane-Detection/ERFNet-CULane-PyTorch/models/sync_bn/__init__.py", line 1, in <module>
    from .functions.sync_bn import *
  File "/home/ssd500A/adas/Codes-for-Lane-Detection/ERFNet-CULane-PyTorch/models/sync_bn/functions/__init__.py", line 1, in <module>
    from .sync_bn import *
  File "/home/ssd500A/adas/Codes-for-Lane-Detection/ERFNet-CULane-PyTorch/models/sync_bn/functions/sync_bn.py", line 6, in <module>
    from .._ext import sync_bn_lib
  File "/home/ssd500A/adas/Codes-for-Lane-Detection/ERFNet-CULane-PyTorch/models/sync_bn/_ext/sync_bn_lib/__init__.py", line 3, in <module>
    from ._sync_bn_lib import lib as _lib, ffi as _ffi
ImportError: /home/ssd500A/adas/Codes-for-Lane-Detection/ERFNet-CULane-PyTorch/models/sync_bn/_ext/sync_bn_lib/_sync_bn_lib.so: undefined symbol: state

**Comment by fantasycheng** [comment]
It seems there are some problem in my installation for PyTorch。
