### ISSUE TITLE
ERFNet_pretrained.tar issue

### ISSUE THREAD

**Issue by yoga-0125** [cardwing/Codes-for-Lane-Detection#267]
I tried to run the train_erfnet.sh in ERFNet-CULane-PyTorch. But the following error appeared: 

=> loading checkpoint './pretrained/ERFNet_pretrained.tar'
#reused param: 302
=> loaded checkpoint 'False' (epoch 16)
Traceback (most recent call last):
  File "train_erfnet.py", line 291, in <module>
    main()
  File "train_erfnet.py", line 103, in main
    validate(val_loader, model, criterion, 0, evaluator)
  File "train_erfnet.py", line 194, in validate
    for i, (input, target, target_exist) in enumerate(val_loader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/gdrive/My Drive/lane_detection/SAD/sad/ERFNet-CULane-PyTorch/dataset/voc_aug.py", line 31, in __getitem__
    image = cv2.imread(os.path.join(self.img_path, self.img_list[idx])).astype(np.float32)
AttributeError: 'NoneType' object has no attribute 'astype'

Any suggestions? Thank you.

**Comment by yoga-0125** [comment]
After updating the list address in voc_aug.py, the error becomes:

=> loading checkpoint './pretrained/ERFNet_pretrained.tar'
#reused param: 302
=> loaded checkpoint 'False' (epoch 16)
Traceback (most recent call last):
  File "train_erfnet.py", line 291, in <module>
    main()
  File "train_erfnet.py", line 103, in main
    validate(val_loader, model, criterion, 0, evaluator)
  File "train_erfnet.py", line 194, in validate
    for i, (input, target, target_exist) in enumerate(val_loader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/collate.py", line 79, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/collate.py", line 79, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 763 and 785 in dimension 3 at /pytorch/aten/src/TH/generic/THTensor.cpp:612
