### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

### ISSUE THREAD

**Issue by SAIVENKATARAJU** [cardwing/Codes-for-Lane-Detection#295]
Traceback (most recent call last):
  File "/home/ubuntu/Codes-for-Lane-Detection/SCNN-Tensorflow/lane-detection-model/tools/test_lanenet.py", line 121, in <module>
    test_lanenet(args.image_path, args.weights_path, args.use_gpu, img_name, args.batch_size, save_dir)
  File "/home/ubuntu/Codes-for-Lane-Detection/SCNN-Tensorflow/lane-detection-model/tools/test_lanenet.py", line 58, in test_lanenet
    test_dataset = lanenet_data_processor_test.DataSet(image_path, batch_size)
  File "/home/ubuntu/Codes-for-Lane-Detection/SCNN-Tensorflow/lane-detection-model/data_provider/lanenet_data_processor_test.py", line 31, in __init__
    self._img_list = self._init_dataset()
  File "/home/ubuntu/Codes-for-Lane-Detection/SCNN-Tensorflow/lane-detection-model/data_provider/lanenet_data_processor_test.py", line 47, in _init_dataset
    for _info in file:
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

**Comment by nisha1729** [comment]
What are you passing as your input?

**Comment by nisha1729** [comment]
For anyone else with the same problem, make sure that for the argument image_path, you pass the path to the text file containing the paths to the input images.
