### ISSUE TITLE
Training SCNN-Tensorflow model

### ISSUE THREAD

**Issue by nisha1729** [cardwing/Codes-for-Lane-Detection#302]
Hi, 
When I try to train the SCNN-Tensorflow model, I get the following error. Could you give some insight into what could be causing this problem?
python=3.5, tensorflow=1.15.0, numpy=1.14.2

```
Traceback (most recent call last):
  File ".../Codes-for-Lane-Detection/SCNN-Tensorflow/lane-detection-model/tools/train_lanenet.py", line 335, in <module>
    train_net(args.dataset_dir, args.weights_path, net_flag=args.net)
  File ".../Codes-for-Lane-Detection/SCNN-Tensorflow/lane-detection-model/tools/train_lanenet.py", line 237, in train_net
    encoding='latin1').item()
  File "...\Python37\lib\site-packages\numpy\lib\npyio.py", line 440, in load
    pickle_kwargs=pickle_kwargs)
  File "...\Python37\lib\site-packages\numpy\lib\format.py", line 727, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False
```

**Comment by nisha1729** [comment]
Could you also mention the correct versions of numpy, tensorflow-gpu and python? I've installed according to the requirements.txt (numpy=1.13.1, tensorflow-gpu=1.15.0 (1.3.0 unavailable), python=3.5) but I still receive a lot of errors. After downgrading numpy to 1.13.1, I received this error:

```
ImportError: DLL load failed: The specified module could not be found.
ImportError: numpy.core.multiarray failed to import

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load
SystemError: PyEval_EvalFrameEx returned a result with an error set
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
2020-08-30 20:11:58.808232: F tensorflow/python/lib/core/bfloat16.cc:675] Check failed: PyBfloat16_Type.tp_base != nullptr 

Process finished with exit code -1073740791 (0xC0000409)
```

**Comment by nisha1729** [comment]
Turns out the versions are tensorflow=1.15.0 and python=3.7.
Solved the error by setting ``allow_pickle = True `` in ```np.load()```
Also needs installing protobuf, thanks to https://github.com/cardwing/Codes-for-Lane-Detection/issues/121
