### ISSUE TITLE
training tusimple lane dataset error parsing training data

### ISSUE THREAD

**Issue by jjzhu** [cardwing/Codes-for-Lane-Detection#60]
by preparing the data using the python code provided by: https://github.com/MaybeShewill-CV/lanenet-lane-detection

python tools/generate_tusimple_dataset.py --src_dir path/to/your/unzipped/file

Traceback (most recent call last):
  File "tools/train_lanenet.py", line 335, in <module>
    train_net(args.dataset_dir, args.weights_path, net_flag=args.net)
  File "tools/train_lanenet.py", line 167, in train_net
    train_dataset = lanenet_data_processor.DataSet(train_dataset_file)
  File "/home/victor/src/Codes-for-Lane-Detection/SCNN-Tensorflow/lane-detection-model/data_provider/lanenet_data_processor.py", line 30, in __init__
    self._img, self._label_instance, self._label_existence = self._init_dataset()
  File "/home/victor/src/Codes-for-Lane-Detection/SCNN-Tensorflow/lane-detection-model/data_provider/lanenet_data_processor.py", line 75, in _init_dataset
    label_existence_list.append([int(info_tmp[2]), int(info_tmp[3]), int(info_tmp[4]), int(info_tmp[5])])
ValueError: invalid literal for int() with base 10:

any idea how to prepare both the tusimple and the BDD dataset?

thanks,

**Comment by cardwing** [comment]
@jjzhu, you need to raise issues in the corresponding repo. Besides, I will release codes which prepare the tusimple and the BDD dataset soon. In this condition, SCNN-Tensorflow can run in three datasets.

**Comment by didiao2017** [comment]
@cardwing sounds great. Looking forward to it.
