### ISSUE TITLE
The training problem

### ISSUE THREAD

**Issue by BoSeal** [cardwing/Codes-for-Lane-Detection#73]
When training, there is always an image path that cannot be found.Why does this happen and how to slove it?
The problem is as follows:

2019-03-13 09:15:04.230468: W tensorflow/core/framework/op_kernel.cc:1198] Not found: laneseg_label_w16/driver_23_30frame/05170644_0680.MP4/04850.png; No such file or directory
2019-03-13 09:15:04.230468: W tensorflow/core/framework/op_kernel.cc:1198] Not found: driver_23_30frame/05170644_0680.MP4/04850.jpg; No such file or directory
E0313 09:15:04.230989 9060 tf_logging.py:102] Exception in QueueRunner: laneseg_label_w16/driver_23_30frame/05170644_0680.MP4/04850.png; No such file or directory
         [[Node: data_augmentation/ReadFile_1 = ReadFile[_device="/job:localhost/replica:0/task:0/device:CPU:0"](data_augmentation/input_producer/Gather_1)]]
Exception in thread QueueRunnerThread-batch/fifo_queue-batch/fifo_queue_enqueue:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/seeingdo_normal/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda3/envs/seeingdo_normal/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/anaconda3/envs/seeingdo_normal/lib/python3.6/site-packages/tensorflow/python/training/queue_runner_impl.py", line 250, in _run
    enqueue_callable()
  File "/home/ubuntu/anaconda3/envs/seeingdo_normal/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1251, in _single_operation_run
    self._session, None, {}, [], target_list, status, None)
  File "/home/ubuntu/anaconda3/envs/seeingdo_normal/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: laneseg_label_w16/driver_23_30frame/05170644_0680.MP4/04850.png; No such file or directory

**Comment by cardwing** [comment]
Just check your image path. It should be easy to fix the path problem.
